config/routes.rb
Omrails::Application.routes.draw do
  get "users/show"

  resources :pins

  devise_for :users
  match 'users/:id' => 'users#show', as: :user
  
  get 'about' => 'pages#about'

  root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :City, :Category

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  							   content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  							   size: { less_than: 5.megabytes }
  validates :City, presence: true

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :image
  validates_uniqueness_of :name
  validates_attachment :image,
                       content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                       size: { less_than: 5.megabytes }
  # attr_accessible :title, :body

  has_many :pins
  has_attached_file :image, styles: { small: "150x150>"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@body_class = 'home'
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	#@pins = @user.pins
  	@pins = @user.pins.order("created_at desc").page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
		<div class="footer">
			<small>
				Any questions, feedback or ideas? <a href="mailto:treasure.your.food@gmail.com">Email Me!</a>
			</small>
		</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Food Treasure", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
        	<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
				</ul>
				<ul class="nav pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "Add +", new_pin_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
        	<li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
				</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Food Treasure</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
		<body class="<%= @body_class %>">

		<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>	

	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
	<div class="hero-unit">
		<h2 class="textinbox">Welcome to Food Treasure!</h2>
		<p>
			<h3 class="textinbox">
				Treasure and recommend the food you love
			</h3>
		</p>
			<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-large" %>
	</div>
<% else %>
	<div class="hero-unit">
		<h1 class="textinbox">Food Treasure</h1>
		<p>
		<h3 class="textinbox">
			A dish so delicious, yummy, om nom nom you’d love to
			- dive into it and whoop of joy?
			Treasure and recommend the food you love!
		</h3>
		</p>
		<p>
			<%= link_to "Sign up to treasure!", new_user_registration_path, class: "btn btn-primary btn-large"  %>
		</p>
	</div>
<% end %>

app/views/pages/about.html.erb
	<% if user_signed_in? %>
		<h1> About Food Treasure </h1>
			<br>
		<h5>
			Just tasted Profiteroles so creamy-chocolaty I'd love to dive into it!
			<p>
			--> This is for Nicole and Juli, they would enjoy it just like me!!
			</p>
		</h5>
		<h5>
			Found Gnocchi so tender and topped with home-made mediterranean tomato sauce that my heart leaps for joy!
			<p>
			--> I'm sure Stefan would be a fan of it too!
			</p>
		</h5>
		<h5>
			 My mouth waters when only seeing the sign of the Mexican Restaurant with the incredibly tasty Burrito!
			 <p>
			--> I bet my collegues from work will try the most spicy one!
			</p>
			<br>
		</h5>
		<h4> 
			Treasure and recommend the food you love! 
			</br>
			<p>
			<br>
			<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-large" %>
			</br>
			</p>
		</h4>
		<br>		

	<% else %>
		<h1> About Food Treasure </h1>
			<br>
		<h5>
			Just tasted Profiteroles so creamy-chocolaty you'd love to dive into it?
		</h5>
		<h5>
			Found Gnocchi so tender and topped with home-made mediterranean tomato sauce that your heart leaps for joy?
		</h5>
		<h5>
			 Your mouth waters when only seeing the sign of the Mexican Restaurant with the incredibly tasty Burrito?
		</h5>
		<br>
		<h4> 
			Treasure and recommend the food you love! 
			</br>
			<p>
			<br>
			<%= link_to "Sign up to treasure!", new_user_registration_path, class: "btn btn-primary btn-large"  %>
			</br>
			</p>
		</h4>
	<% end %>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="hero-unit">
	<h2>Welcome to Food Treasure!</h2>
	</div>
<% else %>
	<div class="hero-unit">
		<h1>Food Treasure</h1>
		<p>
		<h3>
			A dish so delicious, yummy, om nom nom you’d love to
			- dive into it and whoop of joy?
			Treasure and recommend the food you love!
		</h3>
		</p>
		<p>
			<%= link_to "Sign up to treasure!", new_user_registration_path, class: "btn btn-primary btn-large"  %>
		</p>
	</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :image, label: "Upload an image" %>
    <%= f.input :description, placeholder: 'What did you eat? How was the foodexperience? In which restaurant/location?', as: :text, input_html: { rows: "3"} %>
    <%= f.input :City, placeholder: 'Where do you get it?', as: :text, input_html: { rows: "1"} %>
    <%= f.input :Category, :collection => [["pure sweetness", "pure sweetness"], ["hot & spicy", "hot & spicy"], ["light & fresh", "light & fresh"], ["exotic", "exotic"], ["local speciality", "local speciality"], ["solid and classic", "solid and classic"], ["absolutely extraordinary", "absolutely extraordinary"]], as: :radio %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
		City 
		</strong>
		<%= pin.City %>
	</p>
	<p>
		<strong>
		Category
		</strong>
		<%= pin.Category %>
	</p>
		<strong>
			Posted by
		</strong>
			<%= link_to pin.user.name, pin.user %>
	</p>
	
	<% if current_user == pin.user %>
		<p>
		<%= link_to 'Edit', edit_pin_path(pin) %>
		<%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
			  <%= @pin.description %>
			</p>
			<p>
				<strong>
				City
				</strong>
			  <%= @pin.City %>
			</p>
			<p>
				<strong>
				Category
				</strong>
				<%= @pin.Category %>
			</p>
			<p>
				<strong>
				Posted by
				</strong>
			  	<%= link_to @pin.user.name, @pin.user %>
			</p>
			<% if current_user == @pin.user %>
			<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.image? %>
<%= image_tag @user.image(:small) %>
<% else %>
Currently no profile picture
<% end %>

<p>

<% if @user == current_user %>
<%= link_to 'Change it?', edit_user_registration_path(:current) %>
<% end %>

<p>

<div id="pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>